version: '3.9'

services:
  activationbase:
    image: mishankjain111/ai-cps-activationbase:latest
    container_name: activationbasecontainer
    volumes:
      - ai_system:/tmp/activationbase  # External volume
    ports:
      - "8081:8080"
    command: tail -f /dev/null

volumes:
  ai_system:
    external: true  # External volume remains unchanged
